from pathlib import Path
p=Path('MySQL/Replication(GTID)/mysql_gtid_replication.sh')
s=p.read_text()
s=s.replace('SCRIPT_VERSION=1.0.13','SCRIPT_VERSION=1.0.14',1)
needle='''format_bytes() {\n    bytes=${1:-0}\n    awk -v bytes="$bytes" 'BEGIN {\n        split("B KiB MiB GiB TiB", unit, " ")\n        value = bytes + 0\n        index = 1\n        while (value >= 1024 && index < 5) {\n            value /= 1024\n            index++\n        }\n        if (index == 1) printf "%.0f %s", value, unit[index]\n        else printf "%.2f %s", value, unit[index]\n    }'\n}\n\n'''
insert=needle+'''compare_source_replica_gtids() {\n    source_gtid=$(mysql_query source "SELECT REPLACE(REPLACE(@@GLOBAL.gtid_executed,CHAR(10),''),CHAR(13),'');") || die "cannot read Source GTID state"\n    replica_gtid=$(mysql_query replica "SELECT REPLACE(REPLACE(@@GLOBAL.gtid_executed,CHAR(10),''),CHAR(13),'');") || die "cannot read Replica GTID state"\n    q_source_gtid=$(sql_quote "$source_gtid")\n    q_replica_gtid=$(sql_quote "$replica_gtid")\n    replica_extra=$(mysql_query replica "SELECT GTID_SUBTRACT('$q_replica_gtid','$q_source_gtid');") || die "cannot compare Replica extra GTIDs"\n    replica_missing=$(mysql_query replica "SELECT GTID_SUBTRACT('$q_source_gtid','$q_replica_gtid');") || die "cannot compare Replica missing GTIDs"\n    GTID_SOURCE=$source_gtid\n    GTID_REPLICA=$replica_gtid\n    GTID_EXTRA=$replica_extra\n    GTID_MISSING=$replica_missing\n}\n\n'''
if needle not in s: raise SystemExit('format_bytes anchor missing')
s=s.replace(needle,insert,1)
old='''    replica_gtid=$(mysql_query replica "SELECT @@GLOBAL.gtid_executed;") || die "cannot read Replica GTID state"\n    if [ -n "$replica_gtid" ]; then\n        log ""\n        log "============================================================"\n        log "[ACTION REQUIRED] Existing Replica GTID"\n        log "============================================================"\n        warn "Replica gtid_executed: $replica_gtid"\n        log "This is transaction history, not the gtid_mode setting in my.cnf."\n        log "Action  : reset existing channels, binary logs, and Replica GTID history"\n        log "Use only: new/rebuildable Replica with no data or GTID history to preserve"\n        log "Recovery: not automatically reversible"\n        confirm_phrase "Logical restore with SET GTID_PURGED requires a compatible clean GTID state." "RESET REPLICA GTID"\n        replica_ver=$(mysql_query replica "SELECT @@version;")\n        replica_num=$(version_number "$replica_ver")\n        reset_syntax=$(replication_syntax "$replica_ver")\n        if [ "$reset_syntax" = modern ]; then\n            mysql_query replica "STOP REPLICA;" >/dev/null 2>&1 || true\n            mysql_query replica "RESET REPLICA ALL;" >/dev/null 2>&1 || true\n        else\n            mysql_query replica "STOP SLAVE;" >/dev/null 2>&1 || true\n            mysql_query replica "RESET SLAVE ALL;" >/dev/null 2>&1 || true\n        fi\n        if [ "$replica_num" -ge 8004000 ]; then\n            mysql_query replica "RESET BINARY LOGS AND GTIDS;" || die "failed to reset Replica GTIDs"\n        else\n            mysql_query replica "RESET MASTER;" || die "failed to reset Replica GTIDs"\n        fi\n    fi\n'''
new='''    compare_source_replica_gtids\n    if [ -n "$GTID_REPLICA" ]; then\n        log ""\n        log "============================================================"\n        log "[ACTION REQUIRED] Existing Replica GTID history"\n        log "============================================================"\n        log "Source gtid_executed : ${GTID_SOURCE:-NONE}"\n        log "Replica gtid_executed: ${GTID_REPLICA:-NONE}"\n        log "Extra on Replica     : ${GTID_EXTRA:-NONE}"\n        log "Missing on Replica   : ${GTID_MISSING:-NONE}"\n        log "The script never clears GTID execution history automatically."\n        if [ -n "$GTID_EXTRA" ]; then\n            warn "Replica contains GTIDs that are not present on Source. Online dump restore is blocked."\n            warn "Inspect/reconcile those transactions or rebuild/reprovision Replica from the authoritative Source."\n            next_step initialize "After reviewed rebuild/reprovisioning, rerun initialize; do not reset GTID history in place."\n            die "Replica has extra/errant GTIDs; destructive GTID reset is intentionally disabled"\n        fi\n        warn "Replica GTIDs are a subset/equal set of Source, but mysqldump --set-gtid-purged=ON requires a clean compatible target GTID state for automated restore."\n        warn "Use 'already' when this Replica is an existing valid copy that should catch up with GTID auto-positioning, or externally rebuild it before using online-dump."\n        next_step initialize "Choose already for a reviewed existing Replica, or externally rebuild to a clean Replica before online-dump."\n        die "online-dump requires an empty Replica GTID history; no automatic reset is performed"\n    fi\n    [ "${replica_app_tables:-0}" -eq 0 ] || die "online-dump requires an empty Replica application-data state; use already for a reviewed existing Replica or externally rebuild it"\n'''
if old not in s: raise SystemExit('destructive reset block missing')
s=s.replace(old,new,1)
p.write_text(s)
