from pathlib import Path
p=Path('PostgreSQL/postgresql_role_switch_v0.1.22.sh')
s=p.read_text()
old='''    if [ -n "$CANDIDATE_SLOT" ]; then\n        say ""\n        say "Physical Replication Slot"\n        say "  현재 Standby가 physical replication slot을 사용하고 있습니다. 역할 전환 후 former Primary용 slot도 새 Primary에 준비하는 것을 권장합니다."\n        slot_identity=${OLD_PRIMARY_APP:-$(hostname 2>/dev/null || echo former_primary)}\n        slot_default=$(sanitize_identifier "${slot_identity}_slot")\n        REVERSE_SLOT=$(ask "New Primary physical replication slot name (empty = do not use a slot)" "$slot_default") || usage_die "Input cancelled."\n'''
new='''    if [ -n "$CANDIDATE_SLOT" ]; then\n        say ""\n        say "Physical Replication Slot for Former Primary"\n        printf '  Current Primary에 있는 현재 slot_name=%s 는 Selected Standby가 현재 Primary에서 WAL을 받을 때 사용하는 slot입니다.\\n' "$CANDIDATE_SLOT"\n        say "  Planned Switchover 후 replication 방향은 Selected Standby (New Primary) -> Former Primary (Standby)로 반전됩니다."\n        say "  기존 slot은 Current Primary에 존재하므로 New Primary에서 그대로 재사용할 수 없습니다."\n        say "  Former Primary가 slot을 사용하도록 하려면 New Primary에 former Primary용 physical replication slot이 별도로 필요합니다."\n        say "  동일 이름의 적합한 physical slot이 New Primary에 이미 있으면 검증 후 재사용하고, 없으면 promotion 후 생성합니다."\n        slot_identity=${OLD_PRIMARY_APP:-$(hostname 2>/dev/null || echo former_primary)}\n        slot_default=$(sanitize_identifier "${slot_identity}_slot")\n        REVERSE_SLOT=$(ask "New Primary slot for former Primary (empty = do not use a slot)" "$slot_default") || usage_die "Input cancelled."\n'''
if old not in s: raise SystemExit('slot block not found')
s=s.replace(old,new,1)
# Fix pre-existing indentation inconsistency in the no-current-slot branch while touching this area.
s=s.replace('''            slot_identity=${OLD_PRIMARY_APP:-$(hostname 2>/dev/null || echo former_primary)}\n        slot_default=$(sanitize_identifier "${slot_identity}_slot")\n''','''            slot_identity=${OLD_PRIMARY_APP:-$(hostname 2>/dev/null || echo former_primary)}\n            slot_default=$(sanitize_identifier "${slot_identity}_slot")\n''',1)
p.write_text(s)
