from pathlib import Path
p=Path('PostgreSQL/postgresql_role_switch_v0.1.22.sh')
s=p.read_text()
old='''remote_slot_state() {\n    rss_pgdata=$1\n    rss_slot=$2\n    remote_init_exact "$rss_pgdata"\n    rss_state=$(psql_call_var slot "$rss_slot" "SELECT CASE WHEN NOT EXISTS (SELECT 1 FROM pg_replication_slots WHERE slot_name=:'slot') THEN 'absent' WHEN EXISTS (SELECT 1 FROM pg_replication_slots WHERE slot_name=:'slot' AND slot_type='physical' AND active) THEN 'physical_active' WHEN EXISTS (SELECT 1 FROM pg_replication_slots WHERE slot_name=:'slot' AND slot_type='physical' AND NOT active) THEN 'physical_inactive' ELSE 'conflict' END" 2>/dev/null | tr -d '[:space:]') || exit 3\n    printf 'SLOT_STATE\\t%s\\t%s\\n' "$rss_slot" "$rss_state"\n}\n'''
new='''remote_slot_state() {\n    rss_pgdata=$1\n    rss_slot=$2\n    remote_init_exact "$rss_pgdata"\n    # Replication slot names are restricted earlier to [a-z0-9_]. Revalidate on\n    # the remote side before embedding the value in SQL so the state query does\n    # not depend on psql variable interpolation across the SSH transport.\n    case "$rss_slot" in ''|*[!a-z0-9_]*) exit 64 ;; esac\n    rss_count=$(psql_call "SELECT count(*) FROM pg_replication_slots WHERE slot_name='$rss_slot'" 2>/dev/null | tr -d '[:space:]') || exit 3\n    case "$rss_count" in ''|*[!0-9]*) exit 3 ;; esac\n    if [ "$rss_count" -eq 0 ] 2>/dev/null; then\n        rss_state=absent\n    elif [ "$rss_count" -eq 1 ] 2>/dev/null; then\n        rss_row=$(psql_call "SELECT slot_type || E'\\t' || active::text FROM pg_replication_slots WHERE slot_name='$rss_slot'" 2>/dev/null | sed -n '1p') || exit 3\n        rss_type=$(printf '%s\\n' "$rss_row" | awk -F '\\t' '{print $1}')\n        rss_active=$(printf '%s\\n' "$rss_row" | awk -F '\\t' '{print $2}')\n        if [ "$rss_type" != physical ]; then\n            rss_state=conflict\n        else\n            case "$rss_active" in\n                t|true) rss_state=physical_active ;;\n                f|false) rss_state=physical_inactive ;;\n                *) exit 3 ;;\n            esac\n        fi\n    else\n        # slot_name is unique by definition; more than one row indicates an\n        # unexpected catalog/protocol result and must never be treated as absent.\n        exit 3\n    fi\n    printf 'SLOT_STATE\\t%s\\t%s\\n' "$rss_slot" "$rss_state"\n}\n'''
if old not in s: raise SystemExit('remote_slot_state block not found')
s=s.replace(old,new,1)
old='''        css_slot_state=$(printf '%s\\n' "$css_slot_output" | awk -F '\\t' '$1=="SLOT_STATE" {print $3; exit}')\n        case "$css_slot_state" in\n'''
new='''        css_slot_line=$(printf '%s\\n' "$css_slot_output" | awk -F '\\t' '$1=="SLOT_STATE" {print; exit}')\n        [ -n "$css_slot_line" ] || die "Reverse replication slot state check returned no SLOT_STATE record for '$css_reverse_slot'."\n        css_slot_name=$(printf '%s\\n' "$css_slot_line" | awk -F '\\t' '{print $2}')\n        css_slot_state=$(printf '%s\\n' "$css_slot_line" | awk -F '\\t' '{print $3}')\n        [ "$css_slot_name" = "$css_reverse_slot" ] || die "Reverse replication slot state response name mismatch: expected=$css_reverse_slot observed=${css_slot_name:-<empty>}"\n        case "$css_slot_state" in\n'''
if old not in s: raise SystemExit('controller slot parser block not found')
s=s.replace(old,new,1)
p.write_text(s)
